version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: DataImporter.WebApp/Dockerfile
        env_file: 
            - web.env
        volumes:
            - app-volume:/app/wwwroot/
        ports:
            - "44379:80"
        depends_on:
            - db
    dataimporterworker:
        build: 
            context: .
            dockerfile: DataImporter.Worker/Dockerfile
        volumes:
            - app-volume:/app/wwwroot/            
        env_file: 
            - DataImporter.env         
        depends_on: 
            - db
    dataexporterworker:
        build: 
            context: .
            dockerfile: DataExporter.Worker/Dockerfile
        volumes:
            - app-volume:/app/wwwroot/            
        env_file: 
            - DataExporter.env         
        depends_on: 
            - db
    filemailerworker:
        build: 
            context: .
            dockerfile: FileMailer.Worker/Dockerfile
        volumes:
            - app-volume:/app/wwwroot/            
        env_file: 
            - FileMailer.env         
        depends_on: 
            - db                      
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "2357ZAQ%"
            ACCEPT_EULA: "Y"
        ports:
            - "11433:1433"
volumes:
     app-volume: 
        driver: local